### ISSUE TITLE
[Feature] 카드 long press & swipe 제스처

### ISSUE THREAD

**Issue by Minkyeong-Ko** [DeveloperAcademy-POSTECH/MC2-Team14-OXY#11]
## Description
카드를 꾹 눌러서 위/아래로 보내는 제스처 구현

## To-do
- [ ] 카드를 꾹 누르는 제스처 + 드래그 제스처 합치기
- [ ] 카드를 위로 보내기
- [ ] 카드를 아래로 내리기

**Comment by imparang** [comment]
sequence gesture 찾아보시면 될듯요!
