### ISSUE TITLE
[Feature, Fix] Reaction Emoji Animation 수정 및 BackButton 삭제

### ISSUE THREAD

**Issue by Genesis2010** [DeveloperAcademy-POSTECH/MC2-Team14-OXY#122]
## Description
- Reaction Emoji 요소와 개수를 줄일 필요성 제시
- Reaction Emoji Animation 으로 보이는 Emoji 의 수와 크기 조절의 필요성 제시
- `AnonymousLoginLoadingView()` 로드 시 보이는 BackButton 가 필요 없다는 의견
- 각 View 에 선언되어 있는 다른 View 들의 파라미터 값이 빠져 있음

## To-do
- [ ] Reaction Emoji 요소와 개수를 수정 
- [ ] Reaction Emoji Animation 으로 보이는 Emoji 의 수와 크기 조절
- [ ] `AnonymousLoginLoadingView()` 로드 시 보이는 BackButton 삭제
- [ ] `MeetingRoomView` 에서 `CarouselView` 선언 시 빠져있는 파라미터 값 넣기
- [ ] `CarouselView` 에서 `EmojiReactionView` 선언 시 빠져있는 파라미터 값 넣기
