### ISSUE TITLE
[refactor] TimerView

### ISSUE THREAD

**Issue by YeeunKim-archive** [DeveloperAcademy-POSTECH/MC2-Team14-OXY#130]
## To-do
- [ ] 알림 toggle을 누르면 시간이 가지 않는 현상
- [ ] background에서 시간이 가지 않는 현상 : background 에서 시간이 다르게 흐르는 듯
- [ ] 타이머뷰의 상단 navigationbar hidden으로
