### ISSUE TITLE
[Feature] 쉬는시간 타이머뷰 UI

### ISSUE THREAD

**Issue by YeeunKim-archive** [DeveloperAcademy-POSTECH/MC2-Team14-OXY#16]
## Description
쉬는시간 뷰 UI 구현

## ScreenShot
<img width="255" alt="스크린샷 2022-06-09 오후 5 28 20" src="https://user-images.githubusercontent.com/95920991/172802495-24d7a950-d8a2-4cae-8e93-8ac836b22d32.png">

## To-do
- [x] 쉬는시간 타이틀 
- [ ] 쉬는시간 종료 안내 문구
- [x] 프로그래스 **원형바 + 분:초 텍스트**
- [x] 알림 on/off 설정버튼

## Etc
UI제작 단계에서 background mode도 생각해야하는지?

**Comment by imparang** [comment]
단순 UI를 먼저 하시고 그 다음 이슈에서 타이머가 동작하는거 하시고 또 그 다음 이슈에서 백그라운드에서 타이머가 동작하도록 하면 어떨까요?

**Comment by YeeunKim-archive** [comment]
초기 세팅 변경으로 재작업 위해 이슈 종료합니다
