### ISSUE TITLE
[Feature] Firebase Messaging & Functions 연동

### ISSUE THREAD

**Issue by imparang** [DeveloperAcademy-POSTECH/MC2-Team14-OXY#67]
## Description
쉬는 시간 제안, 쉬는 시간 종료 3분 전, 쉬는 시간 종료 Notification 전송을 위한 Firebase 연동

## To-do
- [ ] iOS APN 인증서 등록
- [ ] Firebase Cloud Messging 연동 및 노티 수신 테스트
- [ ] Firebase Functions 연동
