### ISSUE TITLE
[Feature] TestCardView 리팩토링 및 오류 수정

### ISSUE THREAD

**Issue by Minkyeong-Ko** [DeveloperAcademy-POSTECH/MC2-Team14-OXY#75]
## Description
- TestCardView 리팩토링 및 오류 수정

## To-do
- [x] 팀원들이 쉽게 이해할 수 있도록 자세한 주석 달기
- [x] 변수명 직관적으로 바꾸기
- [x] animation is deprecated 오류 수정
